const fs=require("fs"),path=require("path");
const out=path.join(__dirname,"build");
fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,"index.html"),`<!doctype html>
<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#09090b"><title>Fenix Music</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#09090b;color:#fff;font-family:Inter,Arial,sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer}.app{min-height:100vh;padding:28px}.nav{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:28px}.nav button,.card button{background:#18181b;color:#fff;border:1px solid #27272a;border-radius:12px;padding:10px 14px}.nav button.active,.primary{background:#dc2626!important;border-color:#dc2626!important}.page{max-width:1100px;margin:auto}.hero{padding:35px 0}.eyebrow{font-size:12px;letter-spacing:2px;color:#a1a1aa}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:16px}.card{background:#111113;border:1px solid #27272a;border-radius:18px;padding:14px}.cover{width:100%;aspect-ratio:1;border-radius:12px;object-fit:cover;background:#18181b}.muted{color:#a1a1aa}.form{max-width:480px;background:#111113;border:1px solid #27272a;border-radius:18px;padding:20px}.form input,.form textarea,.form select{width:100%;margin:7px 0 15px;padding:12px;border-radius:10px;border:1px solid #27272a;background:#09090b;color:#fff}.player{position:fixed;bottom:0;left:0;right:0;background:#111113eF;border-top:1px solid #27272a;padding:12px;display:flex;gap:12px;align-items:center;justify-content:center}.player button{border:0;border-radius:50%;padding:12px;background:#dc2626;color:white}.spacer{height:80px}@media(max-width:600px){.app{padding:16px}.grid{grid-template-columns:repeat(2,1fr)}}
</style></head><body><div id="root"></div><script>
const root=document.getElementById("root");let tracks=[],user=null,current=null,audio=new Audio();
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(url,opt={}){const r=await fetch("/api"+url,{credentials:"include",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||d.message||"Ошибка");return d}
function nav(page){root.innerHTML='<div class="app"><div class="nav">'+["home","favorites","history","profile","settings"].map(x=>'<button class="'+(page==x?"active":"")+'" onclick="nav(\\''+x+'\\')">'+({home:"Главная",favorites:"Избранное",history:"История",profile:"Профиль",settings:"Настройки"}[x])+"</button>").join("")+'</div><div id="page" class="page"></div><div class="spacer"></div></div>';pageRender(page)}
async function load(){try{tracks=(await api("/tracks")).tracks||[]}catch(e){tracks=[]}try{user=(await api("/auth/me")).user||null}catch(e){user=null}nav("home")}
function pageRender(p){const el=document.getElementById("page");if(p==="home")return home(el);if(p==="profile")return profile(el);if(p==="settings")return settings(el);if(p==="favorites")return list(el,"Избранное",true);if(p==="history")return list(el,"История",false)}
function home(el){el.innerHTML='<div class="hero"><span class="eyebrow">FENIX MUSIC</span><h1>Музыка начинается здесь</h1><p class="muted">Твоя музыкальная вселенная.</p></div><div class="grid">'+tracks.map(trackCard).join("")+"</div>";}
function trackCard(t){return '<div class="card"><img class="cover" src="'+esc(t.cover_url||"https://placehold.co/500x500/18181b/fff?text=FX")+'"><h3>'+esc(t.title)+'</h3><p class="muted">'+esc(t.artist_name||"Unknown")+'</p><button class="primary" onclick="play('+Number(t.id)+')">▶ Слушать</button> <button onclick="fav('+Number(t.id)+')">♥</button></div>"}
async function play(id){current=tracks.find(x=>Number(x.id)===id);if(!current)return;audio.src=current.audio_url||("/api/tracks/"+id+"/audio");audio.play().catch(()=>{});try{await api("/history",{method:"POST",body:JSON.stringify({track_id:id})})}catch(e){}player()}
function player(){if(!current)return;let old=document.querySelector(".player");if(old)old.remove();document.body.insertAdjacentHTML("beforeend",'<div class="player"><b>'+esc(current.title)+'</b><span class="muted">'+esc(current.artist_name||"")+'</span><button onclick="audio.paused?audio.play():audio.pause()">▶</button></div>')}
async function fav(id){try{await api("/favorites",{method:"POST",body:JSON.stringify({track_id:id})});alert("Добавлено в избранное")}catch(e){alert(e.message)}}
async function list(el,title,favmode){if(!user){el.innerHTML='<h1>'+title+'</h1><p>Войди в аккаунт.</p>';return}try{const d=await api(favmode?"/favorites":"/history");const a=d.tracks||d.history||[];el.innerHTML="<h1>"+title+"</h1><div class=grid>"+a.map(trackCard).join("")+"</div>"}catch(e){el.innerHTML="<h1>"+title+"</h1><p>"+esc(e.message)+"</p>"}}
function profile(el){if(!user){el.innerHTML='<div class=form><h1>Войти</h1><input id="email" placeholder="Email или username"><input id="pass" type=password placeholder="Пароль"><button class=primary onclick="login()">Войти</button><hr><h2>Регистрация</h2><input id="regu" placeholder="Username"><input id="rege" placeholder="Email"><input id="regp" type=password placeholder="Пароль"><button class=primary onclick="register()">Создать аккаунт</button></div>';return}el.innerHTML='<div class=form><h1>Профиль</h1><p class=muted>'+esc(user.email||"")+'</p><input id="uname" value="'+esc(user.username||"")+'"><textarea id="bio" placeholder="Расскажи о себе">'+esc(user.bio||"")+'</textarea><button class=primary onclick="saveProfile()">Сохранить</button> <button onclick="logout()">Выйти</button></div>'}
async function login(){try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({login:email.value,email:email.value,password:pass.value})});user=d.user;nav("profile")}catch(e){alert(e.message)}}
async function register(){try{const c=await api("/auth/captcha");const answer=prompt("Введите CAPTCHA: "+c.text);const d=await api("/auth/register",{method:"POST",body:JSON.stringify({username:regu.value,email:rege.value,password:regp.value,captcha:answer,captcha_id:c.id})});user=d.user;nav("profile")}catch(e){alert(e.message)}}
async function saveProfile(){try{const d=await api("/auth/profile",{method:"PUT",body:JSON.stringify({username:uname.value,bio:bio.value})});user=d.user;nav("profile")}catch(e){alert(e.message)}}
async function logout(){await api("/auth/logout",{method:"POST"});user=null;nav("profile")}
function settings(el){el.innerHTML='<div class=form><h1>Настройки</h1><p>Тема: тёмная</p><p>Качество: высокое</p><p>Автоплей: включён</p></div>'}
load();
</script></body></html>`);
